### ISSUE TITLE
Funny menu entries in German UI localisation (DE, and others)

### ISSUE THREAD

**Issue by cweickhmann** [wvdakker/gtkterm#65]
I've noticed that for some reason, the menu entries in the localisation of DE (and in FR, too) are funny.
They display the full menu "path", so to say.

For example, "File" -> "Clear screen" is displayed as "/Datei" -> "/Datei/Bildschirm leeren".
This is really odd and makes the UI unnecessarily cluttered.

If you're okay with it, I'd change the PO file accordingly and create a pull request.

**edit**: Trying to take a screenshot, I've noticed that global shortcuts (like in my case PrintScreen on Gnome) don't work when in GTKTerm's menu. (Reproduce: Click on "/Konfiguration", pulldown menu opens, pressing PrintScreen does not open the screenshot utility. Expected behaviour: It should, no matter what the current menu selection is.)

**Comment by wvdakker** [comment]
Hi,

Yes please send the POT updates. If possible within a few day, then I
can release 1.3 with
the updated files.

/Willem

**Comment by cweickhmann** [comment]
Done. You've got the German i18n now.
Additionally, I've submitted a PR for French. If you've got a native speaker around to double check my French, that'd be great though ;-)

**Comment by wvdakker** [comment]
Fixed in 1.3

**Comment by wentasah** [comment]
BTW, does this mean that 1.3 is released? Or the tag and github release will come later?

**Comment by wvdakker** [comment]
I will release it tomorrow (sunday) and upload it to debian sid.
